# (There's no such thing that is stupid question excepts this one:](https://youtu.be/u9hauSrihYQ?t=864)

# why asking question make people unhappy and how to avoid such thing from a Emacs user perspective?

> 你可以不同意，但是要理解世界上有一些人是这样想的。 --海龙

I would like to know how people think.


# examples



I once talk to people. When I try to take an example, I forget to tell him this is not the thing that I test. The aim is to show the idea. Guess what?

>  YOU MUST BE LYING

I had nothing to say.

Even no chance to clarify. Before the post was deleted, before I know this post will be deleted.

So, I feel that many people do not have the patient to talk to you.

So, I need to study what they are thinking. 

And try to avoid such thing. Next time I talk to them.


# ref

https://emacs-china.org/t/re/11836

https://chaoli.club/index.php/5030/p1#p51326


# 
我经常在各种论坛观摩学习，对这个问题，有一点自己的思考，愿意分享给大家。

首先是自己的结论：我认为与其堵，不如疏。

把真正难的问题，或者说是经过提问者长时间思考的问题，放在一个只有专家才能经常访问到的分区。

而在比较水的区域，做到稍微的提醒，即可。


下面是我自己的经历。我一直在思考，如何提问。这个星期，我带着这个问题，进行了一番实践。


我的问题，很简单，“早上好”，用你的母语怎么说。

不到一个星期，我已经学到了这么多种语言:

```
| alias       | written     | sound           |
|-------------+-------------+-----------------|
| spanish     | Buenos días | bo luo di ya si |
| perian      | صبح بخیر    | so be hei zhi   |
| Hindi       | शुभ प्रभात    | shu pu lu part  |
| Bangladesh  | সুপ্রভাত      | shu bu pa       |
| fr.         | Bonjour     | ben zhu         |
| fr. (Ca)    | Bon matin   | Bon montin      |
| arabic      | صباح الخير  | sa ba hou ha li |
| Ita.        |             |                 | 
| Dogri       |             |                 | 
| Albania     | Miremengjes | mi me man jazz  | 
| Russian     | доброе утро | do bo li wu da  | 
| Philippines | ?? 19 sub?  |                 | 
| Urdu        | صبح بخیر    | su ba be hei    |
| Bulgarian   |             | do bo li wu da  |
```

提问的过程，很简单，不做任何 google，一个微笑，一个问题，至今我还没有发现，有人不愿意乐于回答的，这种看似基础的问题。


在语言上的提问尚且如此，我在思考，为什么我们要限制自己呢？ (也许是论坛服务器流量限制或者...）

换句话讲，如果每一人，都没有了思想负担，这里会乱成一团么?

还是，另外一个世界？



* http://jsomers.net/blog/book-clubs#annotations:Wq_onp34Eeq5lXfNm-Z00g

> What makes a class useful is precisely that it lets you compare notes with your classmates along the way, to float your working theories about a book and see how they sound to others. 
